name: dia
description: A simple dart http server in Koa2 style. Use with dia_router, dia_static, dia_body and other packages
version: 0.1.6
homepage: https://github.com/unger1984/dia

environment:
  sdk: '>=3.8.0 <4.0.0'

resolution: workspace

dev_dependencies:
  lints: ^6.1.0
  test: ^1.29.0
  http: ^1.6.0
