name: dia_cors
description: CORS middleware for Dia http server. Add CORS headers to response. Use it with 'dia' and 'dia_router' packages
version: 0.1.3
homepage: https://github.com/unger1984/dia

environment:
  sdk: '>=3.8.0 <4.0.0'

resolution: workspace

dependencies:
  dia: ^0.1.6

dev_dependencies:
  lints: ^6.1.0
  test: ^1.29.0
  http: ^1.6.0
