name: dia_static
description: The middleware for Dia http server, for serving static files. Make Dia in webserver for static content).
version: 0.1.3
homepage: https://github.com/unger1984/dia

environment:
  sdk: '>=3.8.0 <4.0.0'

resolution: workspace

dependencies:
  dia: ^0.1.6
  path: ^1.9.1
  mime: ^2.0.0
  convert: ^3.1.2

dev_dependencies:
  lints: ^6.1.0
  test: ^1.29.0
  http: ^1.6.0
