name: dia_body
description: Request body parser middleware for Dia http serer. Parse query, x-www-form-urlencoded, json and form-data params and uploaded files form HttpRequest.
version: 0.1.4
homepage: https://github.com/unger1984/dia

environment:
  sdk: '>=3.8.0 <4.0.0'

resolution: workspace

dependencies:
  dia: ^0.1.6
  mime: ^2.0.0
  uuid: ^4.5.2
  http_parser: ^4.1.2

dev_dependencies:
  lints: ^6.1.0
  test: ^1.29.0
  http: ^1.6.0
