name: dia_router
description: A router for Dia. Allow add dia middlewares for handle different url addresses.
version: 0.1.8
homepage: https://github.com/unger1984/dia

environment:
  sdk: '>=3.8.0 <4.0.0'

resolution: workspace

dependencies:
  dia: ^0.1.6
  path_to_regexp: ^0.4.0

dev_dependencies:
  lints: ^6.1.0
  test: ^1.29.0
  http: ^1.6.0
